#!/bin/bash
#----------------------------------------------------
# Sample Slurm job script
#   for TACC Frontera CLX nodes
#
#   *** MPI Job in Normal Queue ***
# 
# Last revised: 20 May 2019
#
# Notes:
#
#   -- Launch this script by executing
#      "sbatch clx.mpi.slurm" on a Frontera login node.
#
#   -- Use ibrun to launch MPI codes on TACC systems.
#      Do NOT use mpirun or mpiexec.
#
#   -- Max recommended MPI ranks per CLX node: 56
#      (start small, increase gradually).
#
#   -- If you're running out of memory, try running
#      fewer tasks per node to give each task more memory.
#
#----------------------------------------------------

#SBATCH -J asym_td                # Job name
#SBATCH -o asym_td.o%j            # Name of stdout output file
#SBATCH -e asym_td.e%j            # Name of stderr error file
#SBATCH -p large                  # Queue (partition) name
#SBATCH -N 2048                   # Total # of nodes 
#SBATCH -n 102400                 # Total # of mpi tasks
#SBATCH -t 12:00:00               # Run time (hh:mm:ss)
#SBATCH --mail-type=all           # Send email at begin and end of job
#SBATCH -A ATM20007               # Project/Allocation name (req'd if you have more than 1)
#SBATCH --mail-user=phyxiaolee@gmail.com

# Any other commands must follow all #SBATCH directives...
module load phdf5
module list
pwd
date

# Launch MPI code... 
ibrun ./reconnection.Linux         # Use ibrun instead of mpirun or mpiexec
